import react,{ useState } from 'react';
import './visadesign.css'
import { BrowserRouter, Routes, Route } from "react-router-dom";
import { Outlet, Link } from "react-router-dom";
import { FaBars } from 'react-icons/fa';
function Visa(){
    const [ismobile,changemobile]=useState(false);
    return (
        <>
        <img src="https://static.wixstatic.com/media/nsplsh_0d01a020e0c94544a01f546f8db16765~mv2.jpg/v1/fill/w_1920,h_973,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/nsplsh_0d01a020e0c94544a01f546f8db16765~mv2.jpg" alt=""  fetchpriority="high" id="fixed"/>
            <front>
                <header>
                    <div>
                    <img src="https://static.wixstatic.com/media/8b7396_8269e2d5b8f14538956e3c4c85e31bea~mv2.png/v1/crop/x_204,y_168,w_655,h_540/fill/w_116,h_98,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/1.png" alt="AaoChalo Logo" srcset="https://static.wixstatic.com/media/8b7396_8269e2d5b8f14538956e3c4c85e31bea~mv2.png/v1/crop/x_204,y_168,w_655,h_540/fill/w_116,h_98,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/1.png" fetchpriority="high" id="topicon" />
                    <Link to="/" id="piclink"><img src="https://static.wixstatic.com/media/8b7396_7049d92c884c425882718caa02f97e61~mv2.png/v1/crop/x_41,y_209,w_425,h_93/fill/w_280,h_61,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/AAO%20Chalo.png" alt="AaoChalo Text Logo"  srcset="https://static.wixstatic.com/media/8b7396_7049d92c884c425882718caa02f97e61~mv2.png/v1/crop/x_41,y_209,w_425,h_93/fill/w_280,h_61,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/AAO%20Chalo.png" fetchpriority="high" id="aaochaloimg"/></Link>
                    </div>
                    <button id="dropdown" onClick={()=>changemobile(!ismobile)}><FaBars/></button>
                    <ul id={ismobile? "hidden":""}>
                    <li><Link to="/Flights" class="link"> Flights </Link></li>
                        <li><Link to="/Trains" class="link"> Trains </Link></li>
                        <li><Link to="/Hotels" class="link"> Hotels </Link></li>
                        <li><Link to="/Visa" class="link"> Visa </Link></li>
                        <li><Link to="/About" class="link"> About </Link></li>
                        <li><Link to="/Contact" class="link">Contact</Link></li>
                        <li><Link to="/Blog" class="link">Blog</Link></li>
                    </ul>
                </header>
                <bigtext>
                    <p id="text"><b>VISA</b></p>
                </bigtext>
                
            </front>
            <content>
                <textvisa>
                    <p id="para">Visa support is one of our extraordinary services. We provide Visa support to those who ask us and make the Visa verification notified with all its progress itinerary. We keep notifying our customers with every single step of Visa verification.</p>
                    <p><b>TOURIST Visa Requirements for AUSTRALIA </b></p>
                    <ul>
                        <li>Scanned Passport.</li>
                        <li>Travel History Scanned (Visa and Entry/Exit Stamp).</li>
                        <li>1 Recent Coloured Photograph (Fresh ones i.e. NOT used earlier for any visa) should be: -
                            <ul>
                                <li>35mm x 45mm in dimension</li>
                                <li>On matte finish paper</li>
                                <li>With White background</li>
                                <li>With 80% face coverage, non-smiling ,without sunglasses, a hat/cap or other head covering, unless the applicant wears such items because of their religious belief or ethnic background not previously used in a visa</li>

                            </ul>
                        </li>
                        <li>Covering letter (Addressed to The Australian High Commission).</li>
                        <li>Personal Latest Bank Statement (3 months)</li>
                        <li>Income Tax Papers for last 03 years</li>
                        <li>Aadhar card is mandatory</li>
                        <li>Occupation proof
                        <ul>
                            <li>In case of Employee - Proof of employment and Pay slip of last 3 months</li>
                            <li>In case the applicant is the proprietor / owner of the company - Cover letter on company`s letter head , company`s 3 month`s bank statement, ITR (for 3 years), company GST and Incorporation Certificate.</li>
                            <li>For student School ID card is required.</li>
                            <li>If the applicant is retired- Proof of retirement, pension statements for the last 3 months; proof of regular income generated by ownership of property or business.</li>
                        </ul>
                        </li>
                        <li>If invited by someone (relative/friend etc), then below 3 documents are also required:
                        <ul>
                            <li>Passport copy and visa copy of invitee</li>
                            <li>Invitation letter</li>
                            <li>Relationship proof between applicant and invite</li>
                        </ul>
                        </li>
                        <li>Processing Time:25-30 working days.</li>
                    </ul>
                </textvisa>
            </content>
        </>
    )
}
export default Visa;